import { useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { apiClient } from '../api/client';

export default function AccountRecoveryPage() {
  const [params] = useSearchParams(); const token = params.get('token');
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(''); try { const result = token ? await apiClient.resetPassword(token, password) : await apiClient.requestPasswordReset(email); setMessage(result.message); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to continue.'); } };
  return <main className="flex min-h-screen items-center justify-center bg-slate-50 p-4 dark:bg-navy-900"><form onSubmit={submit} className="w-full max-w-md space-y-5 rounded-3xl border border-slate-200 bg-white p-7 shadow-sm dark:border-navy-700 dark:bg-navy-800"><div><p className="text-xs font-semibold uppercase tracking-[0.25em] text-amber-600">Account security</p><h1 className="mt-2 text-2xl font-bold text-slate-900 dark:text-slate-100">{token ? 'Choose a new password' : 'Reset your password'}</h1><p className="mt-2 text-sm text-slate-600 dark:text-slate-400">{token ? 'Use a strong password with at least eight characters.' : 'We will send a one-hour reset link to your email address.'}</p></div>{token ? <input required minLength={8} type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="New password" className="w-full rounded-xl border border-slate-300 px-3 py-2.5 dark:border-navy-600" /> : <input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="Email address" className="w-full rounded-xl border border-slate-300 px-3 py-2.5 dark:border-navy-600" />}{error ? <p className="text-sm text-rose-700 dark:text-rose-300">{error}</p> : null}{message ? <p className="text-sm text-emerald-700 dark:text-emerald-300">{message}</p> : null}<button className="w-full rounded-xl bg-slate-900 py-2.5 text-sm font-bold text-amber-400 dark:bg-navy-700">{token ? 'Update password' : 'Send reset link'}</button><Link to="/login" className="block text-center text-sm font-medium text-indigo-700">Back to sign in</Link></form></main>;
}
